# Generated by Django 4.0.4 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
