# Generated by Django 4.0.4 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
